services:
  msa-mysql:
    image: mysql:8.4.3
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: rps_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: 1234
    networks:
      - board_net
    healthcheck:
      start_period: 10s
      start_interval: 5s
      interval: 30s
  gateway:
    build: ../gateway
    image: kjh1016015/gateway:1.0
    ports:
      - "8000:8000"
    environment:
      SPRING_CLOUD_CONSUL_HOST: msa-consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_RABBITMQ_HOST: msa-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - board_net
      
  logs:
    build: ../logs
    image: kjh1016015/logs:1.0
    ports:
      - "8580:8580"
    environment:
      SPRING_RABBITMQ_HOST: msa-rabbitmq
      SPRING_CLOUD_CONSUL_HOST: msa-consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    networks:
      - board_net

  leaderboard:
    build: ../leaderboard
    image: kjh1016015/leaderboard:1.0
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://msa-mysql:3306/rps_db?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_RABBITMQ_HOST: msa-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_CLOUD_CONSUL_HOST: msa-consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    networks:
      - board_net
      
  rpsgame:
    build: ../rpsgame
    image: kjh1016015/rpsgame:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://msa-mysql:3306/rps_db?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_RABBITMQ_HOST: msa-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_CLOUD_CONSUL_HOST: msa-consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    networks:
      - board_net
      
  rps-front:
    build: C:\\SW\\25.02.24 - JS\\react\\rps-front
    image: kjh1016015/rps-front:1.0
    ports:
      - "5173:5173"
    networks:
      - board_net
      
networks:
  board_net:
    external: true